var navbar = '';

navbar += '<div class="navbar">';
navbar += '	<div class="navbar-inner">';
navbar += '		<div class="container">';
navbar += '			<a class="brand" href="../index.html">playmoip</a>';
navbar += '			<ul class="nav">';
navbar += '				<li class="divider-vertical"></li>';
navbar += '				<li><a href="index.html">Transparente</a></li>';
navbar += '				<li><a href="#">Pagamento Direto</a></li>';
navbar += '				<li><a href="index.html">Recorrente</a></li>';
navbar += '				<li><a href="#">Cadastro Integrado</a></li>';
navbar += '				<li><a href="#">Notifica&ccedil;&otilde;es</a></li>';
navbar += '				<li class="divider-vertical"></li>';
navbar += '			</ul>';
navbar += '			<img class="pull-right" src="../img/moip.png" width="60" height="32" style="padding: 5px"/>';
navbar += '			<ul class="nav nav-pills pull-right">';
navbar += '				<li class="dropdown" id="moip-land">';
navbar += '					<a class="dropdown-toggle" data-toggle="dropdown" href="#moip-land">';
navbar += '					  moipLand';
navbar += '					  <b class="caret"></b>';
navbar += '					</a>';
navbar += '					<ul class="dropdown-menu">';
navbar += '						<li>';
navbar += '							<a href="#"><i class="icon-home"></i> configMoip <i class="icon-chevron-left"></i></a>';
navbar += '						</li>';
navbar += '						<li>';
navbar += '							<a href="http://maurokobayashi.github.com/integra-moip"><i class="icon-shopping-cart"></i> integraMoip</a>';
navbar += '						</li>';
navbar += '						<li>';
navbar += '							<a href="#"><i class="icon-play"></i> playMoip</a>';
navbar += '						</li>';
navbar += '						<li class="divider"></li>';
navbar += '						<li>';
navbar += '							</i><a href="http://labs.moip.com.br"><i class="icon-user"></i> moiplabs</a>';
navbar += '						</li>';
navbar += '					</ul>';
navbar += '				</li>';
navbar += '			</ul>';
navbar += '		</div>';
navbar += '	</div>';
navbar += '</div>';

document.write(navbar);